import { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import NavBar from '../components/navbar';
import ChayaTime from '../assests/download.png';
import styles from '../styles/Home.module.css';

export default function Home() {
	const [number, SetNumber] = useState(0);
	return (
		<div className={styles.container}>
			<Head>
				<title>Shops</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='display-flex-row-padding-3'>
				<NavBar />
				<div className='contents-body'>
					<Image src={ChayaTime} />
				</div>
			</div>
		</div>
	);
}
